options:
  docker: true
pipelines:
  default:
    - step:
        image: python:3.5
        name: Tests3.5
        script:
          - python --version
          - pip install -r requirements.txt
          - python setup.py build
          - python setup.py install
          - dlp api setenv -e dev
          - dlp login-secret -e "$TEST_USERNAME" -p "$TEST_PASSWORD" -i "$TEST_CLIENT_ID" -s "$TEST_CLIENT_SECRET"
          - pip install gsutil
          - gsutil -m cp -R gs://sdl-tests-assets/assets tests/
          - python tests/test_examples.py
          - python tests/test_runner.py
          # - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
          # - python setup.py bdist_wheel
          # - mv dist/* dist/dtlpy-latest-py3-none-any.whl
          # - gsutil cp dist/dtlpy-latest-py3-none-any.whl gs://dtlpy/dev
    - step:
        image: python:3.6
        name: Tests3.6
        script:
          - python --version
          - pip install -r requirements.txt
          - python setup.py build
          - python setup.py install
          - dlp api setenv -e dev
          - dlp login-secret -e "$TEST_USERNAME" -p "$TEST_PASSWORD" -i "$TEST_CLIENT_ID" -s "$TEST_CLIENT_SECRET"
          - pip install gsutil
          - gsutil -m cp -R gs://sdl-tests-assets/assets tests/
          - python tests/test_examples.py
          - python tests/test_runner.py
          # - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
          # - python setup.py bdist_wheel
          # - mv dist/* dist/dtlpy-latest-py3-none-any.whl
          # - gsutil cp dist/dtlpy-latest-py3-none-any.whl gs://dtlpy/dev
    - step:
        image: python:3.7
        name: Tests3.7
        script:
          - python --version
          - pip install -r requirements.txt
          - python setup.py build
          - python setup.py install
          - dlp api setenv -e dev
          - dlp login-secret -e "$TEST_USERNAME" -p "$TEST_PASSWORD" -i "$TEST_CLIENT_ID" -s "$TEST_CLIENT_SECRET"
          - pip install gsutil
          - gsutil -m cp -R gs://sdl-tests-assets/assets tests/
          - python tests/test_examples.py
          - python tests/test_runner.py
          # - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
          # - python setup.py bdist_wheel
          # - mv dist/* dist/dtlpy-latest-py3-none-any.whl
          # - gsutil cp dist/dtlpy-latest-py3-none-any.whl gs://dtlpy/dev
  tags:
    "*":
      - step:
          image: python:3.5
          name: Build SDK Container
          script:
            - case "$BITBUCKET_TAG" in "") export BITBUCKET_TAG="build-$BITBUCKET_BUILD_NUMBER"; esac
            - python setup.py bdist_wheel
            - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
            - chmod +x ./build-docker-cpu.sh
            - ./build-docker-cpu.sh $BITBUCKET_TAG
            - chmod +x ./build-docker-gpu.sh
            - ./build-docker-gpu.sh $BITBUCKET_TAG