options:
  docker: true
pipelines:
  tags:
    "*":
      - step:
          image: python:3.5
          name: Build SDK Container
          script:
            - case "$BITBUCKET_TAG" in "") export BITBUCKET_TAG="build-$BITBUCKET_BUILD_NUMBER"; esac
            - python setup.py bdist_wheel
            - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
            - chmod +x ./build-docker-cpu.sh
            - ./build-docker-cpu.sh $BITBUCKET_TAG
            - chmod +x ./build-docker-gpu.sh
            - ./build-docker-gpu.sh $BITBUCKET_TAG