options:
  docker: true
pipelines:
  tags:
    "*":
      - step:
          image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
          name: Build SDK Container
          script:
            - case "$BITBUCKET_TAG" in "") export BITBUCKET_TAG="build-$BITBUCKET_BUILD_NUMBER"; esac
            - apt-get -y update && apt-get install -y python3-pip
            - python3 setup.py bdist_wheel
            - docker login -u _json_key -p "$GCP_KEY" https://gcr.io
            - cp dist/dtlpy-$BITBUCKET_TAG-py3-none-any.whl dist/dtlpy-latest-py3-none-any.whl
            - echo "$GCP_KEY" >> k.json
            - gcloud auth activate-service-account --key-file=k.json
            - gsutil -m cp -R dist/**  gs://dtlpy/dev/
            - chmod +x ./build-docker.sh
            - ./build-docker.sh $BITBUCKET_TAG
            - git checkout -b "$BITBUCKET_TAG"
            - git clone https://$GIT_USER:$GIT_PASSWORD@bitbucket.org/dataloop-ai/piper-agent-runner.git
            - cd piper-agent-runner
            - git config user.email $GIT_EMAIL
            - git checkout master
            - python3 bumpversion.py --hard $BITBUCKET_TAG.0
            - git push --follow-tags
            - cd ..
            - git clone https://$GIT_USER:$GIT_PASSWORD@bitbucket.org/dataloop-ai/piper-agent-proxy.git
            - cd piper-agent-proxy
            - git config user.email $GIT_EMAIL
            - git checkout master
            - python3 bumpversion.py --hard $BITBUCKET_TAG.0
            - git push --follow-tags
            - cd ..
    "run-test-python-3.5.4":
      - step:
          image: python:3.5.4
          name: Tests-3.5.4
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py "$TEST_USER_PROD" "$TEST_PASSWORD_PROD" "$CLIENT_ID_PROD" "$CLIENT_SECRET_PROD"
            - pip install gsutil
            - gsutil -m cp -R gs://dtlpy/assets tests/
            - python tests/test_runner.py
    "run-test-python-3.6.11":
      - step:
          image: python:3.6.11
          name: Tests-3.6.11
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py "$TEST_USER_PROD" "$TEST_PASSWORD_PROD" "$CLIENT_ID_PROD" "$CLIENT_SECRET_PROD"
            - pip install gsutil
            - gsutil -m cp -R gs://dtlpy/assets tests/
            - python tests/test_runner.py
    "run-test-python-3.7.8":
      - step:
          image: python:3.7.8
          name: Tests3.7.8
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py "$TEST_USER_PROD" "$TEST_PASSWORD_PROD" "$CLIENT_ID_PROD" "$CLIENT_SECRET_PROD"
            - pip install gsutil
            - gsutil -m cp -R gs://dtlpy/assets tests/
            - python tests/test_runner.py
    "run-test-python-3.8.4":
      - step:
          image: python:3.8.4
          name: Tests-3.8.4
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py "$TEST_USER_PROD" "$TEST_PASSWORD_PROD" "$CLIENT_ID_PROD" "$CLIENT_SECRET_PROD"
            - pip install gsutil
            - gsutil -m cp -R gs://dtlpy/assets tests/
            - python tests/test_runner.py
    "examples":
      - step:
          image: python:3.5.4
          name: Examples-3.5.4
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py "$TEST_USER_PROD" "$TEST_PASSWORD_PROD" "$CLIENT_ID_PROD" "$CLIENT_SECRET_PROD"
            - pip install gsutil
            - gsutil -m cp -R gs://dtlpy/assets tests/
            - python tests/test_examples.py
